// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Gera o acesso a um usuário no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Gera o acesso a um usuário",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.DefaultResponse-internal_auth_LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove o acesso a um usuário do sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Remove o acesso a um usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Atualiza o Refresh Token do usuário no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Atualiza o Refresh Token do usuário",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "refreshToken",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RefreshInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RefreshResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Registra um novo usuário no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Registra um novo usuário",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_auth.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/message/send": {
            "post": {
                "description": "Envia uma mensagem via email e WhatsApp",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "message"
                ],
                "summary": "Envia uma mensagem",
                "parameters": [
                    {
                        "description": "Message data",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/message.MessageInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.DefaultResponse-message_MessageDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/whatsapp/instance": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Cria uma nova instância do WhatsApp para o usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "whatsapp"
                ],
                "summary": "Cria uma nova instância do WhatsApp",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_whatsapp.createInstanceInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.DefaultResponse-internal_whatsapp_CreateInstanceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/whatsapp/instances": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Busca todas as instâncias do WhatsApp para o usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "whatsapp"
                ],
                "summary": "Busca todas as instâncias do WhatsApp",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.DefaultResponse-internal_whatsapp_GetInstancesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_ThalysSilva_unicast-backend_internal_student.Student": {
            "type": "object",
            "properties": {
                "annotation": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_internal_student.StudentStatus"
                },
                "studentId": {
                    "type": "string"
                }
            }
        },
        "github_com_ThalysSilva_unicast-backend_internal_student.StudentStatus": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "CANCELED",
                "GRADUATED",
                "LOCKED"
            ],
            "x-enum-varnames": [
                "StudentStatusActive",
                "StudentStatusCanceled",
                "StudentStatusGraduated",
                "StudentStatusLocked"
            ]
        },
        "github_com_ThalysSilva_unicast-backend_internal_user.User": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_ThalysSilva_unicast-backend_pkg_api.DefaultResponse-internal_auth_LoginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_auth.LoginResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_ThalysSilva_unicast-backend_pkg_api.DefaultResponse-internal_whatsapp_CreateInstanceResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_whatsapp.CreateInstanceResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_ThalysSilva_unicast-backend_pkg_api.DefaultResponse-internal_whatsapp_GetInstancesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/internal_whatsapp.GetInstancesResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_ThalysSilva_unicast-backend_pkg_api.DefaultResponse-message_MessageDataResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/message.MessageDataResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_auth.LoginInput": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_auth.LoginResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "jwe": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_internal_user.User"
                }
            }
        },
        "internal_auth.RefreshInput": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "internal_auth.RefreshResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_internal_user.User"
                }
            }
        },
        "internal_auth.RegisterInput": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_whatsapp.CreateInstanceResponse": {
            "type": "object",
            "properties": {
                "instanceId": {
                    "type": "string"
                },
                "qrCode": {
                    "type": "string"
                }
            }
        },
        "internal_whatsapp.GetInstancesResponse": {
            "type": "object",
            "properties": {
                "instances": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_whatsapp.Instance"
                    }
                },
                "userEmail": {
                    "type": "string"
                }
            }
        },
        "internal_whatsapp.Instance": {
            "type": "object",
            "required": [
                "phone"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "instanceId": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "internal_whatsapp.createInstanceInput": {
            "type": "object",
            "required": [
                "phone",
                "userId"
            ],
            "properties": {
                "phone": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "message.Attachment": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "fileName": {
                    "type": "string"
                }
            }
        },
        "message.MessageDataResponse": {
            "type": "object",
            "properties": {
                "emailsFailed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_internal_student.Student"
                    }
                },
                "whatsappFailed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ThalysSilva_unicast-backend_internal_student.Student"
                    }
                }
            }
        },
        "message.MessageInput": {
            "type": "object",
            "required": [
                "body",
                "from",
                "jwe",
                "smtp_id",
                "subject",
                "to",
                "whatsapp_id"
            ],
            "properties": {
                "attachment": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/message.Attachment"
                    }
                },
                "body": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "jwe": {
                    "type": "string"
                },
                "smtp_id": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "to": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "whatsapp_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
