definitions:
  github_com_ThalysSilva_unicast-backend_internal_models.Attachment:
    properties:
      data:
        items:
          type: integer
        type: array
      fileName:
        type: string
    type: object
  ? github_com_ThalysSilva_unicast-backend_internal_models.DefaultResponse-github_com_ThalysSilva_unicast-backend_internal_services_LoginResponse
  : properties:
      data:
        $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_services.LoginResponse'
      message:
        type: string
    type: object
  github_com_ThalysSilva_unicast-backend_internal_models.DefaultResponse-internal_handlers_MessageDataResponse:
    properties:
      data:
        $ref: '#/definitions/internal_handlers.MessageDataResponse'
      message:
        type: string
    type: object
  github_com_ThalysSilva_unicast-backend_internal_models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  github_com_ThalysSilva_unicast-backend_internal_models_entities.Student:
    properties:
      annotation:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      phone:
        type: string
      status:
        $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_models_entities.StudentStatus'
      studentId:
        type: string
    type: object
  github_com_ThalysSilva_unicast-backend_internal_models_entities.StudentStatus:
    enum:
    - ACTIVE
    - CANCELED
    - GRADUATED
    - LOCKED
    type: string
    x-enum-varnames:
    - StudentStatusActive
    - StudentStatusCanceled
    - StudentStatusGraduated
    - StudentStatusLocked
  github_com_ThalysSilva_unicast-backend_internal_models_entities.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    required:
    - email
    - name
    type: object
  github_com_ThalysSilva_unicast-backend_internal_services.LoginResponse:
    properties:
      accessToken:
        type: string
      jwe:
        type: string
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_models_entities.User'
    type: object
  github_com_ThalysSilva_unicast-backend_internal_services.RefreshResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_models_entities.User'
    type: object
  internal_handlers.LoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  internal_handlers.MessageDataResponse:
    properties:
      emailsFailed:
        items:
          $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_models_entities.Student'
        type: array
      whatsappFailed:
        items:
          $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_models_entities.Student'
        type: array
    type: object
  internal_handlers.MessageInput:
    properties:
      attachment:
        items:
          $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_models.Attachment'
        type: array
      body:
        type: string
      from:
        type: string
      jwe:
        type: string
      smtp_id:
        type: string
      subject:
        type: string
      to:
        items:
          type: string
        type: array
      whatsapp_id:
        type: string
    required:
    - body
    - from
    - jwe
    - smtp_id
    - subject
    - to
    - whatsapp_id
    type: object
  internal_handlers.RefreshInput:
    properties:
      refreshToken:
        type: string
    required:
    - refreshToken
    type: object
  internal_handlers.RegisterInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Gera o acesso a um usuário no sistema
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_models.DefaultResponse-github_com_ThalysSilva_unicast-backend_internal_services_LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_models.ErrorResponse'
      summary: Gera o acesso a um usuário
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Remove o acesso a um usuário do sistema
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              message:
                type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Remove o acesso a um usuário
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Atualiza o Refresh Token do usuário no sistema
      parameters:
      - description: Refresh token
        in: body
        name: refreshToken
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.RefreshInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_services.RefreshResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_models.ErrorResponse'
      summary: Atualiza o Refresh Token do usuário
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registra um novo usuário no sistema
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.RegisterInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_models.ErrorResponse'
      summary: Registra um novo usuário
      tags:
      - auth
  /message/send:
    post:
      consumes:
      - application/json
      description: Envia uma mensagem via email e WhatsApp
      parameters:
      - description: Message data
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.MessageInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_models.DefaultResponse-internal_handlers_MessageDataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_models.ErrorResponse'
      summary: Envia uma mensagem
      tags:
      - message
swagger: "2.0"
