definitions:
  github_com_ThalysSilva_unicast-backend_internal_student.Student:
    properties:
      annotation:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      phone:
        type: string
      status:
        $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_student.StudentStatus'
      studentId:
        type: string
    type: object
  github_com_ThalysSilva_unicast-backend_internal_student.StudentStatus:
    enum:
    - ACTIVE
    - CANCELED
    - GRADUATED
    - LOCKED
    type: string
    x-enum-varnames:
    - StudentStatusActive
    - StudentStatusCanceled
    - StudentStatusGraduated
    - StudentStatusLocked
  github_com_ThalysSilva_unicast-backend_internal_user.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    required:
    - email
    - name
    type: object
  github_com_ThalysSilva_unicast-backend_pkg_api.DefaultResponse-internal_auth_LoginResponse:
    properties:
      data:
        $ref: '#/definitions/internal_auth.LoginResponse'
      message:
        type: string
    type: object
  github_com_ThalysSilva_unicast-backend_pkg_api.DefaultResponse-internal_whatsapp_createInstanceResponse:
    properties:
      data:
        $ref: '#/definitions/internal_whatsapp.createInstanceResponse'
      message:
        type: string
    type: object
  github_com_ThalysSilva_unicast-backend_pkg_api.DefaultResponse-message_MessageDataResponse:
    properties:
      data:
        $ref: '#/definitions/message.MessageDataResponse'
      message:
        type: string
    type: object
  github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  internal_auth.LoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  internal_auth.LoginResponse:
    properties:
      accessToken:
        type: string
      jwe:
        type: string
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_user.User'
    type: object
  internal_auth.RefreshInput:
    properties:
      refreshToken:
        type: string
    required:
    - refreshToken
    type: object
  internal_auth.RefreshResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_user.User'
    type: object
  internal_auth.RegisterInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  internal_whatsapp.createInstanceInput:
    properties:
      phone:
        type: string
      userId:
        type: string
    required:
    - phone
    - userId
    type: object
  internal_whatsapp.createInstanceResponse:
    properties:
      instanceId:
        type: string
      qrCode:
        type: string
    type: object
  message.Attachment:
    properties:
      data:
        items:
          type: integer
        type: array
      fileName:
        type: string
    type: object
  message.MessageDataResponse:
    properties:
      emailsFailed:
        items:
          $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_student.Student'
        type: array
      whatsappFailed:
        items:
          $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_internal_student.Student'
        type: array
    type: object
  message.MessageInput:
    properties:
      attachment:
        items:
          $ref: '#/definitions/message.Attachment'
        type: array
      body:
        type: string
      from:
        type: string
      jwe:
        type: string
      smtp_id:
        type: string
      subject:
        type: string
      to:
        items:
          type: string
        type: array
      whatsapp_id:
        type: string
    required:
    - body
    - from
    - jwe
    - smtp_id
    - subject
    - to
    - whatsapp_id
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Gera o acesso a um usuário no sistema
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/internal_auth.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.DefaultResponse-internal_auth_LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse'
      summary: Gera o acesso a um usuário
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Remove o acesso a um usuário do sistema
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              message:
                type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Remove o acesso a um usuário
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Atualiza o Refresh Token do usuário no sistema
      parameters:
      - description: Refresh token
        in: body
        name: refreshToken
        required: true
        schema:
          $ref: '#/definitions/internal_auth.RefreshInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_auth.RefreshResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse'
      summary: Atualiza o Refresh Token do usuário
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registra um novo usuário no sistema
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/internal_auth.RegisterInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse'
      summary: Registra um novo usuário
      tags:
      - auth
  /message/send:
    post:
      consumes:
      - application/json
      description: Envia uma mensagem via email e WhatsApp
      parameters:
      - description: Message data
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/message.MessageInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.DefaultResponse-message_MessageDataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse'
      summary: Envia uma mensagem
      tags:
      - message
  /whatsapp/instance:
    post:
      consumes:
      - application/json
      description: Cria uma nova instância do WhatsApp para o usuário
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/internal_whatsapp.createInstanceInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.DefaultResponse-internal_whatsapp_createInstanceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_ThalysSilva_unicast-backend_pkg_api.ErrorResponse'
      summary: Cria uma nova instância do WhatsApp
      tags:
      - whatsapp
swagger: "2.0"
